volumes:
  static:

name: loja-online
services:
  app:
    build: .
    env_file: loja-online/.env
    volumes:
      - static:/usr/src/app/static
    develop:
      watch:
        - action: sync+restart
          path: ./loja-online
          target: /usr/src/app
          initial_sync: true
          ignore:
            - virtualenv

        - action: rebuild
          path: requirements.txt

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.nginx
    volumes:
      - static:/static
    ports:
      - 9000:80
    depends_on:
      - app